class AddTitleToTestCases < ActiveRecord::Migration[5.0]
  def self.up
    add_column :test_cases, :title, :string, null: false, default: "title"

    TestCase.all.each do |test_case|
      test_case.title = "Default title generated by migration AddTitleToTestCases"
      test_case.save!
    end

    change_column_default :test_cases, :title, nil
  end

  def self.down
    remove_column :test_cases, :title
  end
end
